//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientCard()
        {
            this.Talon = new HashSet<Talon>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateBirth { get; set; }
        public int ChronicalId { get; set; }
        public int DispensaryId { get; set; }
        public string Snils { get; set; }

        public string FullName
        {
            get { return $"{LastName} {FirstName} {Patronymic}"; }
        }

        public virtual Chronical Chronical { get; set; }
        public virtual Dispensary Dispensary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talon> Talon { get; set; }
    }
}
