//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talon
    {
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public int OfficeId { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime AdmissionDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Office Office { get; set; }
        public virtual PatientCard PatientCard { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
